In [1]:
import pyspark.sql.functions as F
from data_location import DELTA_LOCATION

from spark_bi.constants import ColNames, Extensions
from spark_bi.spark import FutPathlingContext

pc = FutPathlingContext.create(
    app_name="example-spark-careteams",
)
delta_lake = pc.read.delta(DELTA_LOCATION)

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
26/04/15 13:10:17 WARN Utils: Your hostname, kdh-m1-max.local, resolves to a loopback address: 127.0.0.1; using 10.103.141.9 instead (on interface en0)
26/04/15 13:10:17 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
:: loading settings :: url = jar:file:/Users/kdh/code/fut/spark-bi/.venv/lib/python3.11/site-packages/pyspark/jars/ivy-2.5.3.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /Users/kdh/.ivy2.5.2/cache
The jars for the packages stored in: /Users/kdh/.ivy2.5.2/jars
au.csiro.pathling#library-runtime added as a dependency
io.delta#delta-spark_2.13 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-8cd1c97e-17b8-4d40-9de4-1f4f5ec93368;1.0
	confs: [default]
	found au.csiro.pathling#library-runtime;9.1.0 in central
	found io.delta#delta-spark_2.13;4.0.0 in local-m2-cache
	found io.delta#delta-storage;4.0.0 in local-m2-cache
	found org.antlr#antlr4-runtime;4.13.1 in local-m2-cache
:: resolution report :: resolve 176ms :: artifacts dl 7ms
	:: modules in use:
	au.csiro.pathling#library-runtime;9.1.0 from central in [default]
	io.delta#delta-spark_2.13;4.0.0 from local-m2-cache in [default]
	io.delta#delta-storage;4.0.0 from local-m2-cache in [default]
	org.antlr#antlr4-runtime;4.13.1 from local-m2-cache in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   4   |   0   |   0   |   0   ||   4   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-8cd1c97e-17b8-4d40-9de4-1f4f5ec93368
	confs: [default]
	0 artifacts copied, 4 already retrieved (0kB/6ms)
26/04/15 13:10:18 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

# By aktiv/inaktiv

Ej meningsfyldt for careteams.

# By anvenderløsning

For at finde anvenderløsning bruger vi coexistence-tags der er beskrevet i: https://ehealth-dk.atlassian.net/wiki/spaces/EDTW/pages/2355986433/Multitenancy

Coexistence-tags sættes ikke på careteams, hvorfor vi ikke kan spore, hvilken anvenderløsning, der har oprettet dem.

# By careteam

Ej relevant.

# By diagnosis

In [2]:
(
    delta_lake.view(
        resource="CareTeam",
        select=[
            {
                "column": [
                    {"name": "ct_id", "path": "getResourceKey()"},
                    {
                        "name": ColNames.CREATING_SOLUTION.value,
                        "path": "meta.tag.where(system='http://ehealth.sundhed.dk/cs/ehealth-system').code.first()",
                    },
                ]
            },
            {"forEach": "reasonCode", "column": [{"name": "condition", "path": "coding.code"}]},
        ],
    )
    .groupby("condition")
    .count()
    .toPandas()
)

   condition  count
0       J3.5      4
1       DF70      1
2       DF99      2
3       TBD2      3
4         F2      5
..       ...    ...
70      DI50      7
71      J1.5      3
72      J3.2     15
73     I11.4      1
74      DF20      2

[75 rows x 2 columns]

Vær opmærksom på, at disse tal er fra TRIFORKs testmiljø, og derfor ikke repræsentative.

# By kommune

For at finde et careteams kommune laver vi koblingen:

`Careteam.managingOrganization <-> Organization.municipalityCode`

In [3]:
careteams = delta_lake.view(
    resource="CareTeam",
    select=[
        {
            "column": [
                {"name": "careteam_id", "path": "getResourceKey()"},
                {"name": "org_id", "path": "managingOrganization.first().getReferenceKey()"},
            ]
        }
    ],
)
careteams.filter(F.col("org_id").isNotNull()).head(5)

[Row(careteam_id='CareTeam/3000130813', org_id='Organization/3000037596'),
 Row(careteam_id='CareTeam/3000130845', org_id='Organization/3000037596'),
 Row(careteam_id='CareTeam/3000130877', org_id='Organization/3000037596'),
 Row(careteam_id='CareTeam/3000130909', org_id='Organization/3000037596'),
 Row(careteam_id='CareTeam/3000130941', org_id='Organization/3000037596')]

In [4]:
organizations = delta_lake.view(
    resource="Organization",
    select=[
        {
            "column": [
                {"name": "org_id", "path": "getResourceKey()"},
                {
                    "name": ColNames.MUNICIPALITY_CODE.value,
                    "path": f"extension('{Extensions.EHEALTH_MUNICIPALITY_CODES.value}').valueString",
                },
                {
                    "name": ColNames.REGION_CODE.value,
                    "path": f"extension('{Extensions.EHEALTH_REGION_CODES.value}').valueString",
                },
            ]
        }
    ],
)
organizations.filter(F.col(ColNames.MUNICIPALITY_CODE.value).isNotNull()).head(5)

[Row(org_id='Organization/3000000006', municipality_code='0630', region_code='1083'),
 Row(org_id='Organization/3000000007', municipality_code='0851', region_code='1081'),
 Row(org_id='Organization/3000000009', municipality_code='0787', region_code='1081'),
 Row(org_id='Organization/3000000012', municipality_code='0813', region_code='1081'),
 Row(org_id='Organization/3000000015', municipality_code='0360', region_code='1085')]

In [5]:
joined = careteams.join(organizations, careteams.org_id == organizations.org_id, how="left")

In [6]:
(
    joined.groupBy(ColNames.MUNICIPALITY_CODE.value)
    .agg(F.countDistinct("careteam_id").alias("n_careteams"))
    .orderBy("n_careteams", ascending=False)
    .toPandas()
)

   municipality_code  n_careteams
0               None         4613
1               0851         3106
2               0615          925
3               0791           54
4               0219           46
5               0741           28
6               0101           10
7               0630            1
8               0849            1
9               0400            1
10              0340            1
11              0751            1

På TRIFORKs testmiljø er der kun 2 careteams der er tilknyttet en kommune.

# By organisatorisk enhed

See README.md under "Organistorisk enhed".

# By region

In [7]:
(
    joined.groupBy(ColNames.REGION_CODE.value)
    .agg(F.countDistinct("careteam_id").alias("n_careteams"))
    .orderBy("n_careteams", ascending=False)
    .toPandas()
)

  region_code  n_careteams
0        None         4611
1        1081         3107
2        1082         1008
3        1084           57
4       DK-83            2
5        1085            1
6        1083            1

På TRIFORKs testmiljø er der kun 2 careteams der er tilknyttet en region.