In [1]:
import pyspark.sql.functions as F
from data_location import DELTA_LOCATION

from spark_bi.constants import ColNames, Extensions
from spark_bi.spark import FutPathlingContext

pc = FutPathlingContext.create(
    app_name="example-spark-careplan",
)
delta_lake = pc.read.delta(DELTA_LOCATION)

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
26/04/15 13:10:41 WARN Utils: Your hostname, kdh-m1-max.local, resolves to a loopback address: 127.0.0.1; using 10.103.141.9 instead (on interface en0)
26/04/15 13:10:41 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
:: loading settings :: url = jar:file:/Users/kdh/code/fut/spark-bi/.venv/lib/python3.11/site-packages/pyspark/jars/ivy-2.5.3.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /Users/kdh/.ivy2.5.2/cache
The jars for the packages stored in: /Users/kdh/.ivy2.5.2/jars
au.csiro.pathling#library-runtime added as a dependency
io.delta#delta-spark_2.13 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-6ae7c4ec-9836-4346-8e2d-ff243f5c761d;1.0
	confs: [default]
	found au.csiro.pathling#library-runtime;9.1.0 in central
	found io.delta#delta-spark_2.13;4.0.0 in local-m2-cache
	found io.delta#delta-storage;4.0.0 in local-m2-cache
	found org.antlr#antlr4-runtime;4.13.1 in local-m2-cache
:: resolution report :: resolve 131ms :: artifacts dl 8ms
	:: modules in use:
	au.csiro.pathling#library-runtime;9.1.0 from central in [default]
	io.delta#delta-spark_2.13;4.0.0 from local-m2-cache in [default]
	io.delta#delta-storage;4.0.0 from local-m2-cache in [default]
	org.antlr#antlr4-runtime;4.13.1 from local-m2-cache in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   4   |   0   |   0   |   0   ||   4   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-6ae7c4ec-9836-4346-8e2d-ff243f5c761d
	confs: [default]
	0 artifacts copied, 4 already retrieved (0kB/6ms)
26/04/15 13:10:42 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/04/15 13:10:44 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.

# By anvenderløsning

For at finde anvenderløsning bruger vi coexistence-tags der er beskrevet i: https://ehealth-dk.atlassian.net/wiki/spaces/EDTW/pages/2355986433/Multitenancy

Patienterne selv stammer fra CPR-registret, og har derfor ikke et coexistence-tag. Alle relevante patienter har mindst ét forløb, og derfor tæller vi antal unikke patienter fra episodes of care, og finder disses creating_solution.

In [2]:
from pyspark.sql.functions import col

cp_with_patient_id = delta_lake.view(
    resource="CarePlan",
    select=[
        {
            "column": [
                {"name": "cp_id", "path": "getResourceKey()"},
                {"name": "cp_patient_id", "path": "subject.getReferenceKey()"},
                {
                    "name": ColNames.CREATING_SOLUTION.value,
                    "path": f"meta.tag.where(system='{Extensions.EHEALTH_COLOCATION.value}').code.first()",
                },
            ]
        }
    ],
)
cp_with_patient_id.filter(col("creating_solution").isNotNull()).head(5)

[Row(cp_id='CarePlan/2000018937', cp_patient_id='Patient/1000000328', creating_solution='xb'),
 Row(cp_id='CarePlan/2000018943', cp_patient_id='Patient/1000000328', creating_solution='xb'),
 Row(cp_id='CarePlan/2000018956', cp_patient_id='Patient/1000000328', creating_solution='xb'),
 Row(cp_id='CarePlan/2000018963', cp_patient_id='Patient/1000000328', creating_solution='xb'),
 Row(cp_id='CarePlan/2000018976', cp_patient_id='Patient/1000000328', creating_solution='xb')]

In [3]:
(cp_with_patient_id.groupby("creating_solution").count().toPandas())

  creating_solution  count
0              None  36342
1                xb  15050
2                xa   2195

Bemærk at antallet er for TRIFORKs testmiljø.

# By careteam

In [4]:
careplans_with_team = delta_lake.view(
    resource="CarePlan",
    select=[
        {"column": [{"name": "cp_id", "path": "getResourceKey()"}]},
        {"forEach": "careTeam", "column": [{"name": "cp_team_id", "path": "getReferenceKey()"}]},
    ],
)
careplans_with_team.groupby("cp_team_id").count().toPandas()

               cp_team_id  count
0     CareTeam/3000119523      1
1     CareTeam/3000120254      1
2     CareTeam/3000124214      1
3     CareTeam/3000140581      1
4     CareTeam/3000158413      1
...                   ...    ...
2898  CareTeam/3000262318      1
2899  CareTeam/3000223992      1
2900  CareTeam/3000224136     19
2901  CareTeam/3000221306      3
2902  CareTeam/3000264180      1

[2903 rows x 2 columns]

Bemærk, at dette er fordelingen for TRIFORKs testmiljø.

# By diagnosis

For at finde episode-of-care'ens diagnoser/behandlingsområder skal vi lave koblingen:

`CarePlan.addresses <-> Condition.code`

Vi skal bruge denne beregning flere steder, og genbruger derfor en utility-funktion, der udfører det.

In [5]:
conditions_with_code = delta_lake.view(
    resource="Condition",
    select=[
        {
            "column": [
                {"name": "condition_id", "path": "getResourceKey()"},
                {"name": "diagnosis_code", "path": "code.coding.code"},
            ]
        }
    ],
)

careplans_with_conditions = delta_lake.view(
    resource="CarePlan",
    select=[
        {
            "column": [
                {"name": "cp_id", "path": "getResourceKey()"},
                {"name": "addresses_condition", "path": "addresses.getReferenceKey()"},
            ]
        }
    ],
)

(
    careplans_with_conditions.join(
        conditions_with_code,
        careplans_with_conditions["addresses_condition"] == conditions_with_code["condition_id"],
        how="inner",
    )
    .groupby("diagnosis_code")
    .count()
    .toPandas()
)

  diagnosis_code  count
0            TBD   7045
1           DJ44  46542

Vær opmærksom på, at disse tal er fra TRIFORKs testmiljø, og derfor ikke repræsentative.

# By kommune

Fordelt på den patient de omhandlers bopælskommune:

In [6]:
from spark_bi.dfs import compute_patient2municipality


patients_with_municipality = compute_patient2municipality(delta_lake)

(
    cp_with_patient_id.join(
        patients_with_municipality,
        cp_with_patient_id.cp_patient_id == patients_with_municipality.patient_id,
        "inner",
    )
    .groupby(ColNames.MUNICIPALITY_CODE.value)
    .count()
    .toPandas()
)

   municipality_code  count
0               0671     36
1               0851     12
2               0461     14
3               0201     26
4               0153     20
..               ...    ...
95              0240     44
96              0779     10
97              0840     22
98              0270     20
99              0480      4

[100 rows x 2 columns]

Vær opmærksom på, at disse tal er fra TRIFORKs testmiljø, og derfor ikke repræsentative.

# By organisatorisk enhed

See README.md under "Organistorisk enhed".

# By region

In [7]:
from spark_bi.dfs import compute_patient2region

patients_with_region = compute_patient2region(delta_lake)

(
    cp_with_patient_id.join(
        patients_with_region,
        cp_with_patient_id.cp_patient_id == patients_with_region.patient_id,
        "inner",
    )
    .groupby(ColNames.REGION_CODE.value)
    .count()
    .toPandas()
)

  region_code  count
0       DK-81   4942
1        None      2
2       DK-84  14182
3     UNKNOWN      2
4       DK-82  15538
5       DK-85    918
6       DK-83  18003

Vær opmærksom på, at disse tal er fra TRIFORKs testmiljø, og derfor ikke repræsentative.